file system logic completed
andreyDelay/file-storage pull request #1
Opened 2022-08-14 14:14 UTC by andreyDelay

Очень базово сделал, небольшая путаница с папками и менами, как мне кажется.
Думал сделать под каждую книгу свою папку

2022-08-15 12:45 UTC, kegisa approved these changes

2022-08-15 12:45 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/controller/DownloadFileController.java
> +public class DownloadFileController {
Контроллеры думаю можно объеденить в один

2022-08-15 12:45 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/controller/DownloadFileController.java
> +	@ResponseStatus(HttpStatus.OK)
По умолчанию вроде и так ОК, дублировать не нужно это если это так , могу ошибаться

2022-08-15 12:45 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/config/FileStorageConfig.java
> +public class FileStorageConfig {
давай в пропертис переименуем

2022-08-15 12:45 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/controller/UploadFileController.java
> +	private final FileStorageConfig fileStorageConfig;
Это здесь лишнее, давай перенесем это в сервис, мы же можем оттуда подтянуть пропертис эти. Чтобы контроллер не засорять

2022-08-15 12:45 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/service/FileSystemStorageService.java
> +		var destinationDirectory = getDestinationDirectory(targetFolder);
Эти вары....Не всегода понятно что вообще за ними скрываеся. На боевых задачач только в тестах встречал вары.

2022-08-15 12:45 UTC, kegisa commented on src/main/resources/application.yml
> +  port: 8080
По умолчанию тоже 8080

2022-08-20 15:34 UTC, kegisa approved these changes

2022-08-20 15:34 UTC, kegisa commented on Dockerfile
> +FROM eclipse-temurin:17-jdk-jammy as builder
Почему эту ждк?

2022-08-20 15:34 UTC, kegisa commented on Dockerfile
> +RUN ./mvnw clean install
зачем устанавливать это в репозиторйи котоырй в контейнере?

2022-08-20 15:34 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/service/FileSystemStorageService.java
> +	private final FileStorageProperties storageConfig;
переменную тоже можно было переименовать)

2022-08-20 15:34 UTC, kegisa commented on src/test/java/com/blacklog/filestorage/service/FileSystemStorageServiceTest.java
> +@SpringBootTest
А здесь нужно контекст поднимать? просто создать объект сервсиа и протесить не получается?

2022-09-13 05:44 UTC, kegisa requested changes

2022-09-13 05:44 UTC, kegisa commented on src/main/java/com/blacklog/filestorage/service/FileSystemStorageService.java
> +		log.info("In saveFile method.");
Если нужно логирование до и после метода как у тебя сейчас можно аспекты добавить

2022-09-13 05:44 UTC, kegisa commented on src/test/java/com/blacklog/filestorage/FileStorageApplicationTests.java
> +@ActiveProfiles("test")
А в чем отличие у тебя тестового ямла от стандартоного?

2022-09-14 03:24 UTC, andreyDelay commented on src/main/java/com/blacklog/filestorage/service/FileSystemStorageService.java
> +		log.info("In saveFile method.");
Ок, позднее переделаю на AOP, читаю на работе по-немногу чтобы вспомнить нюансы реализации

2022-09-14 06:47 UTC, kegisa approved these changes

2022-09-14 06:50 UTC, merged